### ISSUE TITLE
Printing the dictionary with color will result in [/color].

### ISSUE THREAD

**Issue by BravoNiceCatch** [Shiva-Shadowsong/loggie#10] opened 2024-11-11 10:01 UTC
I reviewed the code related to the color function, and it seems fine. Could it be a bug within the Godot engine itself?
![image](https://github.com/user-attachments/assets/9c6880a4-406e-4d66-9278-5e10b08cc568)
![image](https://github.com/user-attachments/assets/886c4ae3-2ce5-4a37-8353-6b7933ff5f5a)

**Comment by Shiva-Shadowsong** [comment] 2024-11-11 10:07
Yes, this is a bug with Godot that I have reported, you can read more here: https://github.com/godotengine/godot/issues/97965

This is a duplicate of https://github.com/Shiva-Shadowsong/loggie/issues/3, so I am closing it.

**Closed as not planned by Shiva-Shadowsong** 2024-11-11 10:07 UTC

**Comment by Shiva-Shadowsong** [comment] 2024-11-11 10:11
P.S You can for now avoid this bug if you use colors that are supported by `print_rich` as per the godot [documentation](https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-method-print-rich):

> Color tags only support the following named colors: black, red, green, yellow, blue, magenta, pink, purple, cyan, white, orange, gray. Hexadecimal color codes are not supported.

**Comment by BravoNiceCatch** [comment] 2024-11-11 10:39
> P.S You can for now avoid this bug if you use colors that are supported by `print_rich` as per the godot [documentation](https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-method-print-rich):
> 
> > Color tags only support the following named colors: black, red, green, yellow, blue, magenta, pink, purple, cyan, white, orange, gray. Hexadecimal color codes are not supported.

It doesn't seem to be working; I might have done something wrong, and [/color] still appears.
![image](https://github.com/user-attachments/assets/c42bf339-3b5a-41e6-8cd8-75badd16fac4)

**Comment by Shiva-Shadowsong** [comment] 2024-11-11 10:58
Nevermind, I'm sorry. 
I was thinking of another related issue.

I see no way to mitigate this problem in the current Godot build, it's an issue with `print_rich`, so we'll need to wait for or submit an update that fixes it.
